'use client';
import React, { createContext, useContext, useState, useEffect } from 'react';

export type LangCode = 'en' | 'es' | 'fr' | 'de' | 'ar' | 'zh' | 'pt' | 'ja';

export const LANG_NAMES: Record<LangCode, string> = {
  en: 'English',
  es: 'Español',
  fr: 'Français',
  de: 'Deutsch',
  ar: 'العربية',
  zh: '中文',
  pt: 'Português',
  ja: '日本語',
};

type Dict = Record<string, string>;
type Translations = Record<LangCode, Dict>;

export const T: Translations = {
  en: {
    dashboard: 'Dashboard', accounts: 'Accounts', transfer: 'Transfer',
    checkbooks: 'Checkbooks', vaults: 'Vaults', invest: 'Invest',
    insights: 'Insights', healthScore: 'Health Score', profile: 'Profile',
    notifications: 'Notifications', twofa: '2FA', signOut: 'Sign Out',
    yourAccounts: 'Your Accounts', accountCenter: 'Account Center',
    totalBalance: 'Total Balance', acrossAccounts: 'across all accounts',
    validThru: 'VALID THRU', copyAccountNo: 'Copy Account No.', copied: 'Copied!',
    freezeCard: 'Freeze Card', unfreezeCard: 'Unfreeze Card',
    recentActivity: 'Recent Activity', noTransactions: 'No recent transactions.',
    addAccount: 'Add Account', deposit: 'Deposit', quickActions: 'Quick Actions',
    yourVaults: 'Your Vaults', savingsVaults: 'Savings Vaults', apy: 'APY',
    progress: 'Progress', remaining: 'Remaining', goalReached: 'Goal Reached!',
    createVault: 'Create Vault', topUp: 'Top Up', withdraw: 'Withdraw',
    vaultName: 'Vault Name', targetAmount: 'Target Amount', currency: 'Currency',
    cancel: 'Cancel', create: 'Create', confirm: 'Confirm', amount: 'Amount',
    projectedCompletion: 'Projected Completion', interestEarned: 'Interest Earned',
    investments: 'Investments', investmentCenter: 'Investment Center',
    totalPortfolioValue: 'Total Portfolio Value', thisMonth: 'this month',
    performance30d: '30-Day Performance', assetAllocation: 'Asset Allocation',
    holdings: 'Holdings', equities: 'Equities', fixedIncome: 'Fixed Income',
    realEstate: 'Real Estate', cash: 'Cash', buy: 'Buy', sell: 'Sell',
    loadingPortfolio: 'Loading portfolio...', noPortfolio: 'No portfolio data.',
    loading: 'Loading...', error: 'Error', close: 'Close', save: 'Save',
    edit: 'Edit', delete: 'Delete', submit: 'Submit', back: 'Back', next: 'Next',
    shares: 'Shares', price: 'Price', value: 'Value', plPercent: 'P&L %',
    tradeAsset: 'Trade Asset', selectAsset: 'Select Asset', tradeType: 'Trade Type',
    market: 'Market', limit: 'Limit', orderPlaced: 'Order placed successfully',
    cards: 'Cards', requestCard: 'Request a Card', cardCenter: 'Card Center',
    yourCards: 'Your Cards', standard: 'Standard', platinum: 'Platinum',
    gold: 'Gold', black: 'Black', blackWorldElite: 'Black World Elite',
    annualFee: 'Annual Fee', cashback: 'Cashback', loungeAccess: 'Lounge Access',
    concierge: 'Concierge', travelInsurance: 'Travel Insurance', free: 'Free',
    deliveryDetails: 'Delivery Details', fullName: 'Full Name',
    deliveryAddress: 'Delivery Address', city: 'City', country: 'Country',
    cardRequested: 'Card Requested!',
    requestSubmitted: 'Your card request has been submitted. Estimated delivery:',
    estimatedDelivery: 'Est. Delivery', debitCard: 'Debit', masterCard: 'Mastercard',
    selectTier: 'Select Your Tier', requestNow: 'Request Now',
    goodMorning: 'Good morning', goodAfternoon: 'Good afternoon', goodEvening: 'Good evening',
    financialOverview: 'Here is your financial overview for today',
    recentTransactions: 'Recent Transactions', viewAll: 'View All',
    marketPulse: 'Market Pulse', netWorth: 'Net Worth',
    todayChange: "Today's Change", monthlyGrowth: 'Monthly Growth',
    spendingBreakdown: 'Spending Breakdown',
  },
  es: {
    dashboard: 'Panel', accounts: 'Cuentas', transfer: 'Transferencia',
    checkbooks: 'Chequeras', vaults: 'Bóvedas', invest: 'Invertir',
    insights: 'Análisis', healthScore: 'Puntaje Salud', profile: 'Perfil',
    notifications: 'Notificaciones', twofa: '2FA', signOut: 'Cerrar Sesión',
    yourAccounts: 'Tus Cuentas', accountCenter: 'Centro de Cuentas',
    totalBalance: 'Saldo Total', acrossAccounts: 'en todas las cuentas',
    validThru: 'VÁLIDA HASTA', copyAccountNo: 'Copiar Nº Cuenta', copied: '¡Copiado!',
    freezeCard: 'Congelar Tarjeta', unfreezeCard: 'Descongelar Tarjeta',
    recentActivity: 'Actividad Reciente', noTransactions: 'Sin transacciones recientes.',
    addAccount: 'Agregar Cuenta', deposit: 'Depósito', quickActions: 'Acciones Rápidas',
    yourVaults: 'Tus Bóvedas', savingsVaults: 'Bóvedas de Ahorro', apy: 'TPA',
    progress: 'Progreso', remaining: 'Restante', goalReached: '¡Meta Alcanzada!',
    createVault: 'Crear Bóveda', topUp: 'Recargar', withdraw: 'Retirar',
    vaultName: 'Nombre de Bóveda', targetAmount: 'Monto Objetivo', currency: 'Moneda',
    cancel: 'Cancelar', create: 'Crear', confirm: 'Confirmar', amount: 'Monto',
    projectedCompletion: 'Finalización Proyectada', interestEarned: 'Interés Ganado',
    investments: 'Inversiones', investmentCenter: 'Centro de Inversiones',
    totalPortfolioValue: 'Valor Total del Portafolio', thisMonth: 'este mes',
    performance30d: 'Rendimiento 30 Días', assetAllocation: 'Asignación de Activos',
    holdings: 'Tenencias', equities: 'Acciones', fixedIncome: 'Renta Fija',
    realEstate: 'Inmuebles', cash: 'Efectivo', buy: 'Comprar', sell: 'Vender',
    loadingPortfolio: 'Cargando portafolio...', noPortfolio: 'Sin datos de portafolio.',
    loading: 'Cargando...', error: 'Error', close: 'Cerrar', save: 'Guardar',
    edit: 'Editar', delete: 'Eliminar', submit: 'Enviar', back: 'Atrás', next: 'Siguiente',
    shares: 'Acciones', price: 'Precio', value: 'Valor', plPercent: 'G/P %',
    tradeAsset: 'Operar Activo', selectAsset: 'Seleccionar Activo', tradeType: 'Tipo de Operación',
    market: 'Mercado', limit: 'Límite', orderPlaced: 'Orden colocada exitosamente',
    cards: 'Tarjetas', requestCard: 'Solicitar Tarjeta', cardCenter: 'Centro de Tarjetas',
    yourCards: 'Sus Tarjetas', standard: 'Estándar', platinum: 'Platino',
    gold: 'Oro', black: 'Negro', blackWorldElite: 'Black World Elite',
    annualFee: 'Cuota Anual', cashback: 'Devolución', loungeAccess: 'Sala VIP',
    concierge: 'Conserje', travelInsurance: 'Seguro de Viaje', free: 'Gratis',
    deliveryDetails: 'Detalles de Entrega', fullName: 'Nombre Completo',
    deliveryAddress: 'Dirección de Entrega', city: 'Ciudad', country: 'País',
    cardRequested: '¡Tarjeta Solicitada!', requestSubmitted: 'Su solicitud ha sido enviada. Entrega estimada:',
    estimatedDelivery: 'Entrega Est.', debitCard: 'Débito', masterCard: 'Mastercard',
    selectTier: 'Seleccione Su Nivel', requestNow: 'Solicitar Ahora',
    goodMorning: 'Buenos días', goodAfternoon: 'Buenas tardes', goodEvening: 'Buenas noches',
    financialOverview: 'Aquí está su resumen financiero de hoy',
    recentTransactions: 'Transacciones Recientes', viewAll: 'Ver Todas',
    marketPulse: 'Pulso del Mercado', netWorth: 'Patrimonio Neto',
    todayChange: 'Cambio de Hoy', monthlyGrowth: 'Crecimiento Mensual',
    spendingBreakdown: 'Desglose de Gastos',
  },
  fr: {
    dashboard: 'Tableau de Bord', accounts: 'Comptes', transfer: 'Virement',
    checkbooks: 'Chéquiers', vaults: 'Coffres', invest: 'Investir',
    insights: 'Analyses', healthScore: 'Score Santé', profile: 'Profil',
    notifications: 'Notifications', twofa: '2FA', signOut: 'Déconnexion',
    yourAccounts: 'Vos Comptes', accountCenter: 'Centre de Comptes',
    totalBalance: 'Solde Total', acrossAccounts: 'sur tous les comptes',
    validThru: 'VALIDE JUSQU\'AU', copyAccountNo: 'Copier N° Compte', copied: 'Copié !',
    freezeCard: 'Geler la Carte', unfreezeCard: 'Dégeler la Carte',
    recentActivity: 'Activité Récente', noTransactions: 'Aucune transaction récente.',
    addAccount: 'Ajouter un Compte', deposit: 'Dépôt', quickActions: 'Actions Rapides',
    yourVaults: 'Vos Coffres', savingsVaults: "Coffres d'Épargne", apy: 'TAP',
    progress: 'Progression', remaining: 'Restant', goalReached: 'Objectif Atteint !',
    createVault: 'Créer un Coffre', topUp: 'Recharger', withdraw: 'Retirer',
    vaultName: 'Nom du Coffre', targetAmount: 'Montant Cible', currency: 'Devise',
    cancel: 'Annuler', create: 'Créer', confirm: 'Confirmer', amount: 'Montant',
    projectedCompletion: 'Fin Projetée', interestEarned: 'Intérêts Gagnés',
    investments: 'Investissements', investmentCenter: "Centre d'Investissement",
    totalPortfolioValue: 'Valeur Totale du Portefeuille', thisMonth: 'ce mois',
    performance30d: 'Performance 30 Jours', assetAllocation: "Allocation d'Actifs",
    holdings: 'Avoirs', equities: 'Actions', fixedIncome: 'Revenus Fixes',
    realEstate: 'Immobilier', cash: 'Liquidités', buy: 'Acheter', sell: 'Vendre',
    loadingPortfolio: 'Chargement du portefeuille...', noPortfolio: 'Aucune donnée.',
    loading: 'Chargement...', error: 'Erreur', close: 'Fermer', save: 'Enregistrer',
    edit: 'Modifier', delete: 'Supprimer', submit: 'Soumettre', back: 'Retour', next: 'Suivant',
    shares: 'Parts', price: 'Prix', value: 'Valeur', plPercent: 'G/P %',
    tradeAsset: 'Trader Actif', selectAsset: 'Sélectionner Actif', tradeType: 'Type d\'Ordre',
    market: 'Marché', limit: 'Limite', orderPlaced: 'Ordre passé avec succès',
    cards: 'Cartes', requestCard: 'Demander une Carte', cardCenter: 'Centre des Cartes',
    yourCards: 'Vos Cartes', standard: 'Standard', platinum: 'Platine',
    gold: 'Or', black: 'Noir', blackWorldElite: 'Black World Elite',
    annualFee: 'Frais Annuels', cashback: 'Remboursement', loungeAccess: 'Accès Salon',
    concierge: 'Conciergerie', travelInsurance: 'Assurance Voyage', free: 'Gratuit',
    deliveryDetails: 'Détails de Livraison', fullName: 'Nom Complet',
    deliveryAddress: 'Adresse de Livraison', city: 'Ville', country: 'Pays',
    cardRequested: 'Carte Demandée !', requestSubmitted: 'Votre demande a été soumise. Livraison estimée :',
    estimatedDelivery: 'Livraison Est.', debitCard: 'Débit', masterCard: 'Mastercard',
    selectTier: 'Choisissez Votre Niveau', requestNow: 'Demander Maintenant',
    goodMorning: 'Bonjour', goodAfternoon: 'Bon après-midi', goodEvening: 'Bonsoir',
    financialOverview: "Voici votre aperçu financier d'aujourd'hui",
    recentTransactions: 'Transactions Récentes', viewAll: 'Voir Tout',
    marketPulse: 'Pouls du Marché', netWorth: 'Valeur Nette',
    todayChange: "Variation d'Aujourd'hui", monthlyGrowth: 'Croissance Mensuelle',
    spendingBreakdown: 'Répartition des Dépenses',
  },
  de: {
    dashboard: 'Übersicht', accounts: 'Konten', transfer: 'Überweisung',
    checkbooks: 'Scheckhefte', vaults: 'Tresore', invest: 'Investieren',
    insights: 'Einblicke', healthScore: 'Gesundheits-Score', profile: 'Profil',
    notifications: 'Benachrichtigungen', twofa: '2FA', signOut: 'Abmelden',
    yourAccounts: 'Ihre Konten', accountCenter: 'Kontocenter',
    totalBalance: 'Gesamtguthaben', acrossAccounts: 'über alle Konten',
    validThru: 'GÜLTIG BIS', copyAccountNo: 'Kontonr. kopieren', copied: 'Kopiert!',
    freezeCard: 'Karte einfrieren', unfreezeCard: 'Karte auftauen',
    recentActivity: 'Letzte Aktivität', noTransactions: 'Keine aktuellen Transaktionen.',
    addAccount: 'Konto hinzufügen', deposit: 'Einzahlung', quickActions: 'Schnellaktionen',
    yourVaults: 'Ihre Tresore', savingsVaults: 'Spartresore', apy: 'JAZ',
    progress: 'Fortschritt', remaining: 'Verbleibend', goalReached: 'Ziel erreicht!',
    createVault: 'Tresor erstellen', topUp: 'Aufladen', withdraw: 'Abheben',
    vaultName: 'Tresorname', targetAmount: 'Zielbetrag', currency: 'Währung',
    cancel: 'Abbrechen', create: 'Erstellen', confirm: 'Bestätigen', amount: 'Betrag',
    projectedCompletion: 'Geplanter Abschluss', interestEarned: 'Zinsen verdient',
    investments: 'Investitionen', investmentCenter: 'Investmentzentrum',
    totalPortfolioValue: 'Gesamtportefeuillewert', thisMonth: 'diesen Monat',
    performance30d: '30-Tage-Performance', assetAllocation: 'Vermögensaufteilung',
    holdings: 'Positionen', equities: 'Aktien', fixedIncome: 'Anleihen',
    realEstate: 'Immobilien', cash: 'Bargeld', buy: 'Kaufen', sell: 'Verkaufen',
    loadingPortfolio: 'Portfolio wird geladen...', noPortfolio: 'Keine Portfoliodaten.',
    loading: 'Laden...', error: 'Fehler', close: 'Schließen', save: 'Speichern',
    edit: 'Bearbeiten', delete: 'Löschen', submit: 'Einreichen', back: 'Zurück', next: 'Weiter',
    shares: 'Anteile', price: 'Kurs', value: 'Wert', plPercent: 'G/V %',
    tradeAsset: 'Aktiv handeln', selectAsset: 'Aktiv auswählen', tradeType: 'Auftragsart',
    market: 'Markt', limit: 'Limit', orderPlaced: 'Auftrag erfolgreich erteilt',
    cards: 'Karten', requestCard: 'Karte beantragen', cardCenter: 'Kartencenter',
    yourCards: 'Ihre Karten', standard: 'Standard', platinum: 'Platin',
    gold: 'Gold', black: 'Schwarz', blackWorldElite: 'Black World Elite',
    annualFee: 'Jahresgebühr', cashback: 'Cashback', loungeAccess: 'Loungebesuch',
    concierge: 'Concierge', travelInsurance: 'Reiseversicherung', free: 'Kostenlos',
    deliveryDetails: 'Lieferdetails', fullName: 'Vollständiger Name',
    deliveryAddress: 'Lieferadresse', city: 'Stadt', country: 'Land',
    cardRequested: 'Karte beantragt!', requestSubmitted: 'Ihr Antrag wurde eingereicht. Lieferzeit:',
    estimatedDelivery: 'Voraussichtl. Lieferung', debitCard: 'Debitkarte', masterCard: 'Mastercard',
    selectTier: 'Stufe Wählen', requestNow: 'Jetzt Beantragen',
    goodMorning: 'Guten Morgen', goodAfternoon: 'Guten Tag', goodEvening: 'Guten Abend',
    financialOverview: 'Hier ist Ihre heutige Finanzübersicht',
    recentTransactions: 'Letzte Transaktionen', viewAll: 'Alle Anzeigen',
    marketPulse: 'Marktpuls', netWorth: 'Nettovermögen',
    todayChange: 'Heutige Änderung', monthlyGrowth: 'Monatliches Wachstum',
    spendingBreakdown: 'Ausgabenaufschlüsselung',
  },
  ar: {
    dashboard: 'لوحة التحكم', accounts: 'الحسابات', transfer: 'تحويل',
    checkbooks: 'دفاتر الشيكات', vaults: 'الخزائن', invest: 'استثمار',
    insights: 'رؤى', healthScore: 'نقاط الصحة', profile: 'الملف الشخصي',
    notifications: 'الإشعارات', twofa: '2FA', signOut: 'تسجيل الخروج',
    yourAccounts: 'حساباتك', accountCenter: 'مركز الحسابات',
    totalBalance: 'الرصيد الإجمالي', acrossAccounts: 'عبر جميع الحسابات',
    validThru: 'صالحة حتى', copyAccountNo: 'نسخ رقم الحساب', copied: 'تم النسخ!',
    freezeCard: 'تجميد البطاقة', unfreezeCard: 'إلغاء تجميد البطاقة',
    recentActivity: 'النشاط الأخير', noTransactions: 'لا توجد معاملات حديثة.',
    addAccount: 'إضافة حساب', deposit: 'إيداع', quickActions: 'إجراءات سريعة',
    yourVaults: 'خزائنك', savingsVaults: 'خزائن التوفير', apy: 'العائد السنوي',
    progress: 'التقدم', remaining: 'متبقي', goalReached: 'تم الوصول للهدف!',
    createVault: 'إنشاء خزينة', topUp: 'شحن', withdraw: 'سحب',
    vaultName: 'اسم الخزينة', targetAmount: 'المبلغ المستهدف', currency: 'العملة',
    cancel: 'إلغاء', create: 'إنشاء', confirm: 'تأكيد', amount: 'المبلغ',
    projectedCompletion: 'الإنجاز المتوقع', interestEarned: 'الفائدة المكتسبة',
    investments: 'الاستثمارات', investmentCenter: 'مركز الاستثمار',
    totalPortfolioValue: 'إجمالي قيمة المحفظة', thisMonth: 'هذا الشهر',
    performance30d: 'أداء 30 يومًا', assetAllocation: 'توزيع الأصول',
    holdings: 'الحيازات', equities: 'أسهم', fixedIncome: 'دخل ثابت',
    realEstate: 'عقارات', cash: 'نقد', buy: 'شراء', sell: 'بيع',
    loadingPortfolio: 'جارٍ تحميل المحفظة...', noPortfolio: 'لا توجد بيانات محفظة.',
    loading: 'جارٍ التحميل...', error: 'خطأ', close: 'إغلاق', save: 'حفظ',
    edit: 'تعديل', delete: 'حذف', submit: 'إرسال', back: 'رجوع', next: 'التالي',
    shares: 'أسهم', price: 'السعر', value: 'القيمة', plPercent: 'أرب/خسر %',
    tradeAsset: 'تداول الأصل', selectAsset: 'اختر أصلاً', tradeType: 'نوع التداول',
    market: 'سوق', limit: 'حد', orderPlaced: 'تم تقديم الطلب بنجاح',
    cards: 'البطاقات', requestCard: 'طلب بطاقة', cardCenter: 'مركز البطاقات',
    yourCards: 'بطاقاتك', standard: 'عادية', platinum: 'بلاتينية',
    gold: 'ذهبية', black: 'سوداء', blackWorldElite: 'النخبة العالمية السوداء',
    annualFee: 'الرسوم السنوية', cashback: 'استرداد النقود', loungeAccess: 'الدخول للصالة',
    concierge: 'خدمة الكونسيرج', travelInsurance: 'تأمين السفر', free: 'مجاني',
    deliveryDetails: 'تفاصيل التوصيل', fullName: 'الاسم الكامل',
    deliveryAddress: 'عنوان التوصيل', city: 'المدينة', country: 'البلد',
    cardRequested: 'تم طلب البطاقة!', requestSubmitted: 'تم تقديم طلبك. التوصيل المتوقع:',
    estimatedDelivery: 'التوصيل المتوقع', debitCard: 'بطاقة مدين', masterCard: 'ماستركارد',
    selectTier: 'اختر مستواك', requestNow: 'اطلب الآن',
    goodMorning: 'صباح الخير', goodAfternoon: 'مساء الخير', goodEvening: 'مساء النور',
    financialOverview: 'إليك نظرتك المالية لليوم',
    recentTransactions: 'المعاملات الأخيرة', viewAll: 'عرض الكل',
    marketPulse: 'نبض السوق', netWorth: 'صافي الثروة',
    todayChange: 'تغير اليوم', monthlyGrowth: 'النمو الشهري',
    spendingBreakdown: 'تفصيل الإنفاق',
  },
  zh: {
    dashboard: '仪表盘', accounts: '账户', transfer: '转账',
    checkbooks: '支票本', vaults: '金库', invest: '投资',
    insights: '洞察', healthScore: '健康评分', profile: '个人资料',
    notifications: '通知', twofa: '双重认证', signOut: '退出登录',
    yourAccounts: '您的账户', accountCenter: '账户中心',
    totalBalance: '总余额', acrossAccounts: '跨所有账户',
    validThru: '有效期至', copyAccountNo: '复制账号', copied: '已复制！',
    freezeCard: '冻结卡片', unfreezeCard: '解冻卡片',
    recentActivity: '近期活动', noTransactions: '近期无交易。',
    addAccount: '添加账户', deposit: '存款', quickActions: '快捷操作',
    yourVaults: '您的金库', savingsVaults: '储蓄金库', apy: '年利率',
    progress: '进度', remaining: '剩余', goalReached: '目标达成！',
    createVault: '创建金库', topUp: '充值', withdraw: '提取',
    vaultName: '金库名称', targetAmount: '目标金额', currency: '货币',
    cancel: '取消', create: '创建', confirm: '确认', amount: '金额',
    projectedCompletion: '预计完成', interestEarned: '已赚利息',
    investments: '投资', investmentCenter: '投资中心',
    totalPortfolioValue: '投资组合总价值', thisMonth: '本月',
    performance30d: '30日表现', assetAllocation: '资产配置',
    holdings: '持仓', equities: '股票', fixedIncome: '固定收益',
    realEstate: '房地产', cash: '现金', buy: '买入', sell: '卖出',
    loadingPortfolio: '加载投资组合...', noPortfolio: '无投资组合数据。',
    loading: '加载中...', error: '错误', close: '关闭', save: '保存',
    edit: '编辑', delete: '删除', submit: '提交', back: '返回', next: '下一步',
    shares: '份额', price: '价格', value: '价值', plPercent: '盈亏 %',
    tradeAsset: '交易资产', selectAsset: '选择资产', tradeType: '交易类型',
    market: '市价', limit: '限价', orderPlaced: '订单已成功提交',
    cards: '卡片', requestCard: '申请卡片', cardCenter: '卡片中心',
    yourCards: '您的卡片', standard: '标准', platinum: '铂金',
    gold: '黄金', black: '黑色', blackWorldElite: '黑色世界精英',
    annualFee: '年费', cashback: '返现', loungeAccess: '贵宾休息室',
    concierge: '礼宾服务', travelInsurance: '旅行保险', free: '免费',
    deliveryDetails: '配送详情', fullName: '全名',
    deliveryAddress: '配送地址', city: '城市', country: '国家',
    cardRequested: '卡片已申请！', requestSubmitted: '您的申请已提交。预计到达：',
    estimatedDelivery: '预计配送', debitCard: '借记卡', masterCard: '万事达卡',
    selectTier: '选择您的级别', requestNow: '立即申请',
    goodMorning: '早上好', goodAfternoon: '下午好', goodEvening: '晚上好',
    financialOverview: '以下是您今日的财务概览',
    recentTransactions: '最近交易', viewAll: '查看全部',
    marketPulse: '市场脉搏', netWorth: '净资产',
    todayChange: '今日变动', monthlyGrowth: '月度增长',
    spendingBreakdown: '支出分析',
  },
  pt: {
    dashboard: 'Painel', accounts: 'Contas', transfer: 'Transferência',
    checkbooks: 'Talões', vaults: 'Cofres', invest: 'Investir',
    insights: 'Análises', healthScore: 'Score de Saúde', profile: 'Perfil',
    notifications: 'Notificações', twofa: '2FA', signOut: 'Sair',
    yourAccounts: 'Suas Contas', accountCenter: 'Central de Contas',
    totalBalance: 'Saldo Total', acrossAccounts: 'em todas as contas',
    validThru: 'VÁLIDO ATÉ', copyAccountNo: 'Copiar Nº Conta', copied: 'Copiado!',
    freezeCard: 'Congelar Cartão', unfreezeCard: 'Descongelar Cartão',
    recentActivity: 'Atividade Recente', noTransactions: 'Nenhuma transação recente.',
    addAccount: 'Adicionar Conta', deposit: 'Depósito', quickActions: 'Ações Rápidas',
    yourVaults: 'Seus Cofres', savingsVaults: 'Cofres de Poupança', apy: 'TAP',
    progress: 'Progresso', remaining: 'Restante', goalReached: 'Meta Alcançada!',
    createVault: 'Criar Cofre', topUp: 'Recarregar', withdraw: 'Sacar',
    vaultName: 'Nome do Cofre', targetAmount: 'Valor Alvo', currency: 'Moeda',
    cancel: 'Cancelar', create: 'Criar', confirm: 'Confirmar', amount: 'Valor',
    projectedCompletion: 'Conclusão Prevista', interestEarned: 'Juros Ganhos',
    investments: 'Investimentos', investmentCenter: 'Central de Investimentos',
    totalPortfolioValue: 'Valor Total da Carteira', thisMonth: 'este mês',
    performance30d: 'Desempenho 30 Dias', assetAllocation: 'Alocação de Ativos',
    holdings: 'Posições', equities: 'Ações', fixedIncome: 'Renda Fixa',
    realEstate: 'Imóveis', cash: 'Dinheiro', buy: 'Comprar', sell: 'Vender',
    loadingPortfolio: 'Carregando carteira...', noPortfolio: 'Nenhum dado de carteira.',
    loading: 'Carregando...', error: 'Erro', close: 'Fechar', save: 'Salvar',
    edit: 'Editar', delete: 'Excluir', submit: 'Enviar', back: 'Voltar', next: 'Próximo',
    shares: 'Ações', price: 'Preço', value: 'Valor', plPercent: 'L/P %',
    tradeAsset: 'Negociar Ativo', selectAsset: 'Selecionar Ativo', tradeType: 'Tipo de Ordem',
    market: 'Mercado', limit: 'Limite', orderPlaced: 'Ordem enviada com sucesso',
    cards: 'Cartões', requestCard: 'Solicitar Cartão', cardCenter: 'Central de Cartões',
    yourCards: 'Seus Cartões', standard: 'Padrão', platinum: 'Platina',
    gold: 'Ouro', black: 'Preto', blackWorldElite: 'Black World Elite',
    annualFee: 'Taxa Anual', cashback: 'Cashback', loungeAccess: 'Acesso à Sala VIP',
    concierge: 'Concierge', travelInsurance: 'Seguro Viagem', free: 'Grátis',
    deliveryDetails: 'Detalhes de Entrega', fullName: 'Nome Completo',
    deliveryAddress: 'Endereço de Entrega', city: 'Cidade', country: 'País',
    cardRequested: 'Cartão Solicitado!', requestSubmitted: 'Sua solicitação foi enviada. Entrega estimada:',
    estimatedDelivery: 'Entrega Est.', debitCard: 'Débito', masterCard: 'Mastercard',
    selectTier: 'Selecione Seu Nível', requestNow: 'Solicitar Agora',
    goodMorning: 'Bom dia', goodAfternoon: 'Boa tarde', goodEvening: 'Boa noite',
    financialOverview: 'Aqui está sua visão financeira de hoje',
    recentTransactions: 'Transações Recentes', viewAll: 'Ver Tudo',
    marketPulse: 'Pulso do Mercado', netWorth: 'Patrimônio Líquido',
    todayChange: 'Variação de Hoje', monthlyGrowth: 'Crescimento Mensal',
    spendingBreakdown: 'Detalhamento de Gastos',
  },
  ja: {
    dashboard: 'ダッシュボード', accounts: '口座', transfer: '振込',
    checkbooks: '小切手帳', vaults: '金庫', invest: '投資',
    insights: 'インサイト', healthScore: '健康スコア', profile: 'プロフィール',
    notifications: '通知', twofa: '2段階認証', signOut: 'サインアウト',
    yourAccounts: 'あなたの口座', accountCenter: '口座センター',
    totalBalance: '合計残高', acrossAccounts: 'すべての口座',
    validThru: '有効期限', copyAccountNo: '口座番号をコピー', copied: 'コピーしました！',
    freezeCard: 'カードを凍結', unfreezeCard: 'カードの凍結を解除',
    recentActivity: '最近の活動', noTransactions: '最近の取引はありません。',
    addAccount: '口座を追加', deposit: '入金', quickActions: 'クイックアクション',
    yourVaults: 'あなたの金庫', savingsVaults: '貯蓄金庫', apy: '年利率',
    progress: '進捗', remaining: '残り', goalReached: '目標達成！',
    createVault: '金庫を作成', topUp: 'チャージ', withdraw: '引き出し',
    vaultName: '金庫名', targetAmount: '目標金額', currency: '通貨',
    cancel: 'キャンセル', create: '作成', confirm: '確認', amount: '金額',
    projectedCompletion: '完了予定', interestEarned: '獲得利息',
    investments: '投資', investmentCenter: '投資センター',
    totalPortfolioValue: 'ポートフォリオ総額', thisMonth: '今月',
    performance30d: '30日間パフォーマンス', assetAllocation: '資産配分',
    holdings: '保有資産', equities: '株式', fixedIncome: '固定利付',
    realEstate: '不動産', cash: '現金', buy: '買い', sell: '売り',
    loadingPortfolio: 'ポートフォリオを読み込み中...', noPortfolio: 'データなし。',
    loading: '読み込み中...', error: 'エラー', close: '閉じる', save: '保存',
    edit: '編集', delete: '削除', submit: '送信', back: '戻る', next: '次へ',
    shares: '口数', price: '価格', value: '価値', plPercent: '損益 %',
    tradeAsset: '資産を取引', selectAsset: '資産を選択', tradeType: '注文種類',
    market: '成行', limit: '指値', orderPlaced: '注文が正常に送信されました',
    cards: 'カード', requestCard: 'カードを申請', cardCenter: 'カードセンター',
    yourCards: 'あなたのカード', standard: 'スタンダード', platinum: 'プラチナ',
    gold: 'ゴールド', black: 'ブラック', blackWorldElite: 'ブラックワールドエリート',
    annualFee: '年会費', cashback: 'キャッシュバック', loungeAccess: 'ラウンジ利用',
    concierge: 'コンシェルジュ', travelInsurance: '旅行保険', free: '無料',
    deliveryDetails: '配送詳細', fullName: '氏名',
    deliveryAddress: '配送先住所', city: '市区町村', country: '国',
    cardRequested: 'カードを申請しました！', requestSubmitted: '申請を受け付けました。到着予定：',
    estimatedDelivery: '到着予定', debitCard: 'デビット', masterCard: 'マスターカード',
    selectTier: 'ランクを選択', requestNow: '今すぐ申請',
    goodMorning: 'おはようございます', goodAfternoon: 'こんにちは', goodEvening: 'こんばんは',
    financialOverview: '本日の財務概要をご確認ください',
    recentTransactions: '最近の取引', viewAll: 'すべて見る',
    marketPulse: 'マーケットパルス', netWorth: '純資産',
    todayChange: '本日の変動', monthlyGrowth: '月次成長',
    spendingBreakdown: '支出内訳',
  },
};

interface LangCtx {
  lang: LangCode;
  setLang: (l: LangCode) => void;
  t: (key: string) => string;
}

const Ctx = createContext<LangCtx>({ lang: 'en', setLang: () => {}, t: (k) => k });

export function LangProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<LangCode>('en');

  useEffect(() => {
    try {
      const saved = localStorage.getItem('londway_lang') as LangCode | null;
      if (saved && T[saved]) setLangState(saved);
    } catch {}
  }, []);

  const setLang = (l: LangCode) => {
    setLangState(l);
    try { localStorage.setItem('londway_lang', l); } catch {}
  };

  const t = (key: string) => T[lang]?.[key] ?? T.en[key] ?? key;

  return <Ctx.Provider value={{ lang, setLang, t }}>{children}</Ctx.Provider>;
}

export function useLang() { return useContext(Ctx); }
